"""empty message

Revision ID: 82957135dde7
Revises: 4bbf73a7cfc8
Create Date: 2024-07-08 15:24:38.965697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82957135dde7'
down_revision = '4bbf73a7cfc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=256),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)

    # ### end Alembic commands ###
